# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Dokka documentation Generation
      run: ./gradlew dokkaHtml
    - uses: codecov/codecov-action@v1
      with:
        directory: ./build/reports/jacoco/test/
        flags: unitttests
        fail_ci_if_error: true
        verbose: true
    - name: Push Documentation to Host
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
        git config --global user.email "github@markreuter.org"
        git config --global user.name "Mark Reuter"
        git clone https://github.com/reutermj/reutermj.github.io/
        cd reutermj.github.io/
        rm -rf dokka
        mv ../build/dokka/ .
        git remote set-url origin https://reutermj:$API_TOKEN_GITHUB@github.com/reutermj/reutermj.github.io
        git add -A
        git commit -m "A test commit message"
        git push origin main
